<?php
// +----------------------------------------------------------------------
// | 全影集团 [ 纯粹、极致到零 ]
// +----------------------------------------------------------------------
// | Copyright (c) 2017 http://www.7192.com All rights reserved.
// +----------------------------------------------------------------------
// | Author: wuzhenguo <wuzhenguook@gmail.com> <The Best Word!!!>
// +----------------------------------------------------------------------
namespace app\index\controller;

use app\custom\model\Templet;
use app\index\model\Template;
use think\Controller;

class Index extends Controller
{
    protected $page = 20;
    protected function _initialize()
    {
        $account = getUserByCooki("custom");
        if ($account) {
            $info = explode('_',$account);
            $this->assign('name',$info[1]);
        }
        $this->assign('account', $account);
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $templateM = new Template();
        $cate = input('cate', 0, 'int');
        $map['status'] = 1;
        $list = $templateM->getAllTemplate($map,6);
        $this->assign('list', $list);
        $this->assign('cate', $cate);
        return view('index1');
    }

    //模板展示
    public function template_show()
    {
        $id = input('id', 0, 'int');

        $templateM = new Templet();
        $templateInfo = $templateM->getProductById($id);
        $res = is_file(ROOT_PATH . "public" . DS . "xml" . DS . $templateInfo['model_num'] . "_" . $templateInfo['userid'] . ".xml");
        if (!$res) {
            $images = $templateM->getImgByIdAndUid($id, $templateInfo['userid']);
            $vedios = $templateM->getMvByIdAndUid($id, $templateInfo['userid']);
            $text = $templateM->getTextByIdAndUid($id, $templateInfo['userid']);
            $texts = explode(";", $text['text']);
            //生成xml
            $flg = _getXML($templateInfo['userid'], $templateInfo['model_num'], $images, $texts, $vedios);
//            $flg = _getXMLFor4($templateInfo['userid'],$templateInfo['model_num'],$images,$texts,$vedios);
        }
        $this->assign('template', $templateInfo);
        return view();
    }

    /**
     * 分类页面
     */
    public function cates()
    {
        $templateM = new Template();
        $cate = input('cate', 0, 'int');
        $page = input('page',0,'int');
        if (!$page) {
            $page = $this->page;
        }
        $map['status'] = 1;
        $list = $templateM->getAllTemplate($map,$page);
        $this->assign('list', $list);
        $this->assign('cate', $cate);
        return view();
    }

    /**
     * 查看模板播放详情
     */
    public function mvShow()
    {
        $id = input('id', 0, 'int');
        $is_edit = input('isedit', 0, 'int');
        //获取是否登录
        $account = getUserByCooki("custom");
        if ($account) {
            $is_login = '<input type="hidden" id="is-login" value="1">';
        } else {
            $is_login = '<input type="hidden" id="is-login" value="0">';
        }
        if ($is_edit) {
            $btn = '<div class="btns"><a href="javascript:void(0);" id="free-trial">制作视频</a></div>';
        } else {
            $btn = '';
        }
        //获取模板信息
        $tem = new Template();
        $model = $tem->getTemplateById($id);
        $num = $tem->getEditNumByModelId($id);
        $content = '<div class="previewlayer" id="layer-box"> <div class="closed" onclick="closeLayer()">×</div> <div class="contm clearfix">  <div class="video fl">';
        $content .= '<video width="100%" height="100%" controls="controls" style="background:#5C595A;" id="video" autoplay="autoplay" loop="loop">
                        <source src="' . $model['template'] . '" type="video/mp4">
                        <object data="movie.mp4"  width="100%" height="100%">
                        <embed src="movie.swf" width="100%" height="100%">
                        </object> 
                        </video>
                        </div>';
        $content .= '<div class="word fr"> <span><b>' . $model['model_name'] . '</b><i>适合宽屏展示</i></span>
                            <ul>
                                <li><img src="/static/index/images/grpico1.png"><i>' . $model['time'] . '</i></li>
                                <li><img src="/static/index/images/grpico3.png"><i>' . "可替换" . array_sum($num['img_num']) . "张图片</i>" . '
                                </li>
                                <li><img src="/static/index/images/grpico2.png"><i>' . "可修改" . array_sum($num['text_num']) . "处文字" . '</i></li>
                                <li><img src="/static/index/images/grpico2.png"><label>' . "简介：</label>" . $model['content'] . '</li>
                                ' . $btn . '
                            </ul>
                        </div>';
        $content .= '</div>' . $is_login . '</div> <div class="graybg block" id="graybg"></div>';

//        var_exp($content);die();
        return ['data' => $content, "message" => "获取成功"];
    }

    /**
     * 获取首页分类的内容
     */
    public function getCate()
    {
        $cate = input('cate',0,'int');
        $type = input('type',0,'int');

        $tem = new Template();
        $map['cate'] = $cate;
        $map['type'] = $type;
        $map['status'] = 1;

        $models = $tem->getAllTemplate($map,6);
        return ['error'=>0,'data'=>$models];
    }
}


